name: Create search index for docs
# trigger on vercel deployment
on:
  deployment_status:    

jobs:
  typesense-docsearch-scraper:
    name: Typesense DocSearch Scraper
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: sudo apt-get install jq
      - name: 'Create env file'
        run: |
          touch .env
          echo TYPESENSE_API_KEY="${{ secrets.TYPESENSE_API_KEY }}" >> .env
          echo TYPESENSE_HOST=${{ secrets.TYPESENSE_HOST }} >> .env
          echo TYPESENSE_PORT=${{ secrets.TYPESENSE_PORT }} >> .env
          echo TYPESENSE_PROTOCOL=${{ secrets.TYPESENSE_PROTOCOL }} >> .env
          cat .env
      - name: Run scraper
        run: docker run --env-file=.env -e "CONFIG=$(cat ./config.json | jq -r tostring)" typesense/docsearch-scraper

      
      
      
